version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Sao_Paulo
    open-pull-requests-limit: 5
    versioning-strategy: increase
    groups:
      production-safe-updates:
        dependency-type: production
        update-types:
          - patch
          - minor
      development-safe-updates:
        dependency-type: development
        update-types:
          - patch
          - minor

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:30"
      timezone: America/Sao_Paulo
    open-pull-requests-limit: 3
    groups:
      actions-safe-updates:
        update-types:
          - patch
          - minor
