export const classificacaoValues = [
  'Dispensa de Ponto',
  'CCFG',
  'Cessão',
  'Concursos',
  'Contratação',
  'Consultas',
  'Inventário',
  'Expediente Parlamentar',
  'MP',
  'Representação Judicial',
  'DP',
  'PGM',
  'Recurso',
  'Financeiro',
  'Demanda Interna',
  'Permuta',
  'Diversos',
  'Outros',
] as const;
