-- Preparação completa do banco para a Central de Demandas — Expansão.
-- Esta migração substitui a versão inicial, que ainda não foi aplicada em produção.

create schema if not exists private;

create table public.perfis_usuarios (
  id uuid primary key references auth.users(id) on delete cascade,
  nome text not null default '',
  email text not null unique,
  setor text not null default '',
  nivel text not null default 'leitor'
    check (nivel in ('administrador', 'editor', 'leitor')),
  status text not null default 'pendente'
    check (status in ('ativo', 'pendente', 'inativo')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.sme_demandas (
  id bigint generated by default as identity primary key,
  numero text not null unique,
  tipo text not null check (tipo in ('Expediente', 'Processo', 'Outros')),
  assunto text not null,
  responsavel text not null default '',
  limite1 date,
  limite2 date,
  status text not null check (status in (
    'Aguardando Andamento', 'Tramitado', 'Para Assinatura',
    'Encerrado', 'Sobrestado', 'Ajustar'
  )),
  setor text not null default '',
  classificacao text not null default '',
  created_by uuid references auth.users(id),
  updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.sme_historico (
  id bigint generated by default as identity primary key,
  demanda_id bigint not null references public.sme_demandas(id) on delete cascade,
  status_novo text not null,
  setor text not null default '',
  comentario text not null,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

alter table public.perfis_usuarios enable row level security;
alter table public.sme_demandas enable row level security;
alter table public.sme_historico enable row level security;

create or replace function private.is_active()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.perfis_usuarios p
    where p.id = (select auth.uid()) and p.status = 'ativo'
  );
$$;

create or replace function private.can_edit()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.perfis_usuarios p
    where p.id = (select auth.uid())
      and p.status = 'ativo'
      and p.nivel in ('administrador', 'editor')
  );
$$;

create or replace function private.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.perfis_usuarios p
    where p.id = (select auth.uid())
      and p.status = 'ativo'
      and p.nivel = 'administrador'
  );
$$;

revoke all on function private.is_active() from public;
revoke all on function private.can_edit() from public;
revoke all on function private.is_admin() from public;
grant usage on schema private to authenticated;
grant execute on function private.is_active() to authenticated;
grant execute on function private.can_edit() to authenticated;
grant execute on function private.is_admin() to authenticated;

create policy "perfil próprio ou administração pode consultar perfis"
on public.perfis_usuarios for select to authenticated
using (id = (select auth.uid()) or (select private.is_admin()));

create policy "administração gerencia perfis"
on public.perfis_usuarios for update to authenticated
using ((select private.is_admin()))
with check ((select private.is_admin()));

create policy "usuários ativos consultam demandas"
on public.sme_demandas for select to authenticated
using ((select private.is_active()));

create policy "editores criam demandas"
on public.sme_demandas for insert to authenticated
with check ((select private.can_edit()));

create policy "editores atualizam demandas"
on public.sme_demandas for update to authenticated
using ((select private.can_edit()))
with check ((select private.can_edit()));

create policy "editores excluem demandas"
on public.sme_demandas for delete to authenticated
using ((select private.can_edit()));

create policy "usuários ativos consultam histórico"
on public.sme_historico for select to authenticated
using ((select private.is_active()));

create policy "editores registram histórico"
on public.sme_historico for insert to authenticated
with check ((select private.can_edit()));

revoke all on table public.perfis_usuarios from anon, authenticated;
revoke all on table public.sme_demandas from anon, authenticated;
revoke all on table public.sme_historico from anon, authenticated;
grant select on table public.perfis_usuarios to authenticated;
grant update (nivel, status, setor) on table public.perfis_usuarios to authenticated;
grant select, insert, update, delete on table public.sme_demandas to authenticated;
grant select, insert on table public.sme_historico to authenticated;
grant usage, select on all sequences in schema public to authenticated;

alter publication supabase_realtime add table public.sme_demandas;
alter publication supabase_realtime add table public.sme_historico;

create or replace function private.touch_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  if tg_table_name = 'sme_demandas' then
    new.updated_by = (select auth.uid());
  end if;
  return new;
end;
$$;

create trigger perfis_usuarios_touch_updated_at
before update on public.perfis_usuarios
for each row execute function private.touch_updated_at();

create trigger sme_demandas_touch_updated_at
before update on public.sme_demandas
for each row execute function private.touch_updated_at();

create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.email is null or lower(new.email) not like '%@rioeduca.net' then
    raise exception 'Apenas e-mails @rioeduca.net são permitidos.';
  end if;

  insert into public.perfis_usuarios (id, nome, email, nivel, status)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'nome', ''),
    lower(new.email),
    'leitor',
    'pendente'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

revoke all on function private.touch_updated_at() from public;
revoke all on function private.handle_new_user() from public;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function private.handle_new_user();

create or replace function public.criar_sme_demanda(
  p_numero text,
  p_tipo text,
  p_assunto text,
  p_responsavel text,
  p_limite1 date,
  p_limite2 date,
  p_status text,
  p_setor text,
  p_classificacao text
)
returns public.sme_demandas
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_demanda public.sme_demandas;
begin
  insert into public.sme_demandas (
    numero, tipo, assunto, responsavel, limite1, limite2, status,
    setor, classificacao, created_by, updated_by
  ) values (
    p_numero, p_tipo, p_assunto, coalesce(p_responsavel, ''), p_limite1,
    p_limite2, p_status, coalesce(p_setor, ''), coalesce(p_classificacao, ''),
    (select auth.uid()), (select auth.uid())
  ) returning * into v_demanda;

  insert into public.sme_historico (
    demanda_id, status_novo, setor, comentario, created_by
  ) values (
    v_demanda.id, v_demanda.status, v_demanda.setor,
    'Demanda cadastrada no sistema.', (select auth.uid())
  );

  return v_demanda;
end;
$$;

create or replace function public.atualizar_status_sme_demanda(
  p_demanda_id bigint,
  p_novo_status text,
  p_comentario text
)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_setor text;
begin
  update public.sme_demandas
  set status = p_novo_status, updated_by = (select auth.uid())
  where id = p_demanda_id
  returning setor into v_setor;

  if not found then
    raise exception 'Demanda não encontrada.';
  end if;

  insert into public.sme_historico (
    demanda_id, status_novo, setor, comentario, created_by
  ) values (
    p_demanda_id, p_novo_status, coalesce(v_setor, ''),
    coalesce(p_comentario, ''), (select auth.uid())
  );
end;
$$;

revoke all on function public.criar_sme_demanda(text, text, text, text, date, date, text, text, text) from public;
revoke all on function public.atualizar_status_sme_demanda(bigint, text, text) from public;
grant execute on function public.criar_sme_demanda(text, text, text, text, date, date, text, text, text) to authenticated;
grant execute on function public.atualizar_status_sme_demanda(bigint, text, text) to authenticated;
