-- Criar tabela de demandas
CREATE TABLE IF NOT EXISTS public.sme_demandas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero text NOT NULL,
    tipo text NOT NULL CHECK (tipo IN ('Expediente', 'Processo', 'Outros')),
    assunto text NOT NULL,
    responsavel text,
    limite1 text,
    limite2 text,
    status text NOT NULL CHECK (status IN ('Aguardando Andamento', 'Tramitado', 'Para Assinatura', 'Encerrado', 'Sobrestado', 'Ajustar')),
    setor text,
    classificacao text,
    created_at timestamptz DEFAULT now()
);

-- Criar tabela de histórico de comentários
CREATE TABLE IF NOT EXISTS public.sme_historico (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    demanda_id bigint REFERENCES public.sme_demandas(id) ON DELETE CASCADE NOT NULL,
    data_hora text NOT NULL,
    status_novo text NOT NULL,
    setor text,
    comentario text NOT NULL,
    created_at timestamptz DEFAULT now()
);

-- Habilitar RLS
ALTER TABLE public.sme_demandas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sme_historico ENABLE ROW LEVEL SECURITY;

-- Políticas de Acesso: Apenas usuários autenticados @rioeduca.net podem ler e escrever
CREATE POLICY "Acesso completo para usuários @rioeduca.net autenticados" 
ON public.sme_demandas 
FOR ALL 
TO authenticated 
USING (auth.jwt() ->> 'email' LIKE '%@rioeduca.net')
WITH CHECK (auth.jwt() ->> 'email' LIKE '%@rioeduca.net');

CREATE POLICY "Acesso completo ao histórico para usuários @rioeduca.net autenticados" 
ON public.sme_historico 
FOR ALL 
TO authenticated 
USING (auth.jwt() ->> 'email' LIKE '%@rioeduca.net')
WITH CHECK (auth.jwt() ->> 'email' LIKE '%@rioeduca.net');
